name: Backend Lint

on:
  workflow_call:

jobs:
  backend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Backend lint placeholder
        run: echo "Backend lint will be added with flake8 in the future."
