name: 交大資工考古題系統 考古題缺失回報
description: 回報新版考古題系統中缺失的考古題
title: "[考古題缺失] <課程名稱> - <教授>"
labels: ["missing-exam"]
body:
  - type: markdown
    attributes:
      value: |
        ## 交大資工考古題系統 考古題缺失回報

        近期有同學反映新版考古題系統中部分考古題資料有遺漏或缺失的情況。  
        若你在新版系統中發現資料遺漏、檔案缺失或與舊版不符的情況，請協助在下方填寫。  

        我們會在確認後，於此 Issue 回覆對應的 **Google Drive 檔案連結**，  
        若可行，也請將補件轉為 **PDF** 並上傳至新版考古題系統。  

        一起維護並完善考古題系統，讓學弟妹擁有更完整的學習資源！  

        🔗 [舊版考古題系統資料](https://docs.google.com/spreadsheets/d/1D2ikOt6OPi-Y-Ujscqlcn4mMReSWTHyfp77bOX1H6uI/edit?usp=sharing)

        > 標題格式請依照課程名稱及授課教授更改，例如：  
        > `[考古題缺失] 微積分(一) - 余啟哲`

  - type: textarea
    id: readable_filename
    attributes:
      label: 檔名 Readable Filename
      description: 請依據舊版考古題系統資料中的 `readable_filename` 欄位填寫缺失的檔案名稱。若有多個檔案，請分行列出。
      placeholder: 例如：2979__微積分(一)__王夏聲__2018__other__Calculus-王夏聲-Autumn2018.zip
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 備註 Notes
      description: 若有補充資訊可在此提供。
