name: CI/CD Pipeline

on:
  push:
    branches: ["**"]

permissions:
  contents: read
  packages: write

jobs:
  frontend-lint:
    uses: ./.github/workflows/frontend-lint.yml

  backend-lint:
    uses: ./.github/workflows/backend-lint.yml

  frontend-test:
    needs:
      - frontend-lint
      - backend-lint
    uses: ./.github/workflows/frontend-test.yml

  backend-test:
    needs:
      - frontend-lint
      - backend-lint
    uses: ./.github/workflows/backend-test.yml

  frontend-build-image:
    needs:
      - frontend-test
      - backend-test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/frontend-build-image.yml
    secrets: inherit

  backend-build-image:
    needs:
      - frontend-test
      - backend-test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/backend-build-image.yml
    secrets: inherit

  deploy:
    needs:
      - frontend-build-image
      - backend-build-image
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
