name: CI/CD Pipeline

on:
  push:
    branches: ["**"]

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
