name: Test

on:
  workflow_call:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare backend env
        run: |
          cp backend/.env.example backend/.env
          cat <<'EOF' >> backend/.env
          SECRET_KEY=${{ secrets.BACKEND_SECRET_KEY }}
          OAUTH_CLIENT_ID=${{ secrets.BACKEND_OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET=${{ secrets.BACKEND_OAUTH_CLIENT_SECRET }}
          EOF

      - name: Prepare frontend env
        run: cp frontend/.env.example frontend/.env

      - name: Prepare docker env
        run: cp docker/.env.example docker/.env

      - name: Start core services
        run: docker compose -f docker/docker-compose.dev.yml up -d db redis minio
      
      - name: Initialize database
        run: docker compose -f docker/docker-compose.dev.yml run --rm backend uv run python app/db/init_db.py

      - name: Run backend tests
        run: docker compose -f docker/docker-compose.dev.yml run --rm backend uv run pytest

      - name: Tear down
        if: always()
        run: docker compose -f docker/docker-compose.dev.yml down --volumes --remove-orphans

  frontend-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Placeholder frontend unit tests
        run: echo "Frontend unit tests are not configured yet."

  frontend-e2e:
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Placeholder frontend E2E tests
        run: echo "Frontend E2E tests are not configured yet."
